// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq8SjGhCcQ-NfcPAyKSLq1sAOcQ5U98UM',
    appId: '1:1027220963414:web:3254d9b8e6a4a7d98f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    authDomain: 'beltei.firebaseapp.com',
    databaseURL: 'https://beltei-default-rtdb.firebaseio.com',
    storageBucket: 'beltei.appspot.com',
    measurementId: 'G-HF7MCELH92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7zBVe3DmhLcoaTbK0y58wiGXw4LgZuWM',
    appId: '1:1027220963414:android:824773268b7951768f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    databaseURL: 'https://beltei-default-rtdb.firebaseio.com',
    storageBucket: 'beltei.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5tftCQAFSXhNGvlhoq4sAKeyWfXl_L24',
    appId: '1:1027220963414:ios:7747761e0e1c2c9d8f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    databaseURL: 'https://beltei-default-rtdb.firebaseio.com',
    storageBucket: 'beltei.appspot.com',
    androidClientId: '1027220963414-0jntm1kd815tftanctq5a3p0olf4ui5i.apps.googleusercontent.com',
    iosClientId: '1027220963414-o2duf4cbhns3pt629r2p3phtosik0kja.apps.googleusercontent.com',
    iosBundleId: 'kh.edu.beltei.mad',
  );
}
